from enum import Enum


# All paths are constants and stored in the configuration directory in 'pathsAndDictionaries' yaml file.
# They are read into the Paths enum from which all other classes source all path strings.
# However for tests, the absolute paths are directed towards the "tests" directory, so tests should never need to
# access the yaml configuration file.
#
# All paths are absolute paths unless prefix with an "REL" which indicates they are relative.
# All paths are prefixed with "PATH"
class TPLS(Enum):

    # ABSOLUTE PATHS FOR TESTS ROOT
    MC_TESTS = "/Users/u0120577/PycharmProjects/MutateCompute/tests"

    # CONFIGURATION FILES FROM MAIN DIRECTORY (i.e. real data)
    CONFIG_FOR_READ_ONLY = "/Users/u0120577/PycharmProjects/MutateCompute/configuration"
    # INPUT FILES FROM MAIN DIRECTORY (i.e. real data)
    INPUT_FOR_READ_ONLY = "/Users/u0120577/PycharmProjects/MutateCompute/input_data"

    # REPOSITORY OF PDBs and FASTAs
    REPO_PDB_FASTA = '/Users/u0120577/REPO_PDB_FASTA'

    # These relative paths might not be used - entire config dir gets copied as a whole into /tests/ at start of tests.
    REL_CONFIG = "/configuration"
    REL_CONFIG_AGAD = "/configuration/agadir_config"
    REL_CONFIG_JOBQ = "/configuration/cluster_jobq"
    REL_CONFIG_FX = "/configuration/foldx_config"
    REL_CONFIG_GLOBAL_OPTIONS = "/configuration/global_options"
    REL_CONFIG_FX_ACRUNSCRIPT = "/configuration/foldx_config/ac_runscript"
    REL_CONFIG_FX_BMRUNSCRIPT = "/configuration/foldx_config/bm_runscript"

    # ABSOLUTE PATH BUILT FROM ROOT AND RELATIVE PATHS
    MC_TESTS_CONFIG = MC_TESTS + REL_CONFIG
    MC_TESTS_CONFIG_AGAD = MC_TESTS + REL_CONFIG_AGAD
    MC_TESTS_CONFIG_JOBQ = MC_TESTS + REL_CONFIG_JOBQ
    MC_TESTS_CONFIG_FX = MC_TESTS + REL_CONFIG_FX
    MC_TESTS_CONFIG_GLOBAL_OPTIONS = MC_TESTS + REL_CONFIG_GLOBAL_OPTIONS
    MC_TESTS_CONFIG_FX_ACRUNSCRIPT = MC_TESTS + REL_CONFIG_FX_ACRUNSCRIPT
    MC_TESTS_CONFIG_FX_BMRUNSCRIPT = MC_TESTS + REL_CONFIG_FX_BMRUNSCRIPT

    # REFERENCE FILES - NOTE: THESE ARE ONLY USED FOR TESTS
    REL_REFFILES = "/reference_files"
    # ABSOLUTE PATH BUILT FROM ROOT AND RELATIVE PATHS
    MC_TESTS_REFFILES = MC_TESTS + REL_REFFILES

    # INPUT PATHS ONLY
    # e.g. /tests/input_data/<pdbname>/all_mutants/<fxmutantchainname>
    REL_INPUT = "/input_data"
    REL_ALL_MUTANTS = "/all_mutants"
    # ABSOLUTE PATH BUILT FROM ROOT AND RELATIVE PATHS
    MC_TESTS_INPUT = MC_TESTS + REL_INPUT

    # OUTPUT PATHS ONLY
    # e.g.#1: tests/output_data/<pdbname>/foldx/build_model/<fxmutantchainname>
    # e.g.#2: tests/output_data/<pdbname>/mutate_fasta
    REL_OUTPUT = "/output_data"
    REL_FX_AC = "/foldx/analyse_complex"
    REL_FX_BM = "/foldx/build_model"
    REL_MUTATE_FASTA = "/mutate_fasta"
    # ABSOLUTE PATH BUILT FROM ROOT AND RELATIVE PATHS
    MC_TESTS_OUTPUT = MC_TESTS + REL_OUTPUT

    DICT_AA_1TO3 = {'A': 'ALA', 'C': 'CYS', 'D': 'ASP', 'E': 'GLU', 'F': 'PHE', 'G': 'GLY', 'H': 'HIS', 'I': 'ILE',
                    'K': 'LYS', 'L': 'LEU', 'M': 'MET', 'N': 'ASN', 'P': 'PRO', 'Q': 'GLN', 'R': 'ARG', 'S': 'SER',
                    'T': 'THR', 'V': 'VAL', 'W': 'TRP', 'Y': 'TYR'}
    DICT_AA_3TO1 = {'ALA': 'A', 'CYS': 'C', 'ASP': 'D', 'GLU': 'E', 'PHE': 'F', 'GLY': 'G', 'HIS': 'H', 'H1S': 'H',
                    'H2S': 'H', 'ILE': 'I', 'LYS': 'K', 'LEU': 'L', 'MET': 'M', 'ASN': 'N', 'PRO': 'P', 'GLN': 'Q',
                    'ARG': 'R', 'SER': 'S', 'THR': 'T', 'VAL': 'V', 'TRP': 'W', 'TYR': 'Y'}
    LIST_ALL_20_AA = ['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W',
                      'Y']

    ZEUS_R_EXE = "/software/shared/apps/general/R/3.1.2/bin/Rscript"
    ZEUS_FOLDX_EXE = "/switchlab/group/tools/FoldX_2015/FoldX"
    ZEUS_AGADIR_EXE = "/switchlab/group/tools/agadir_10042012/agadirwrapper"
    ZEUS_QSUB_EXE = "/opt/sge/bin/lx-amd64/"

    LOCAL_R_EXE = "/usr/local/bin/R"
    LOCAL_FOLDX_EXE = "/Users/u0120577/SNPEFFECT/executables/FoldX"
    LOCAL_AGADIR_EXE = "/switchlab/group/tools/agadir_10042012/agadirwrapper"

    # FASTA SEQUENCES
    FASTA_SEQ_1_A = 'RVYLTFDELRETKTSEYFSLSHHPLDYRILLMDEDQDRIYVGSKDHILSLNINNISQEALSVFWPASTIKVEECKMAGKDPTHGCGNFVRVIQTFN' \
                    'RTHLYVCGSGAFSPVCTYLNRGRRSEDQVFMIDSKCESGKGRCSFNPNVNTVSVMINEELFSGMYIDFMGTDAAIFRSLTKRNAVRTDQHNSKWLS' \
                    'EPMFVDAHVIPDGTDPNDAKVYFFFKEKLTDNNRSTKQIHSMIARICPNDTGGLRSLVNKWTTFLKARLVCSVTDEDGPETHFDELEDVFLLETDN' \
                    'PRTTLVYGIFTTSSSVFKGSAVCVYHLSDIQTVFNGPFAHKEGPNHQLISYQGRIPYPRPGTCPGGAFTPNMRTTKEFPDDVVTFIRNHPLMYNSI' \
                    'YPIHKRPLIVRIGTDYKYTKIAVDRVNAADGRYHVLFLGTDRGTVQKVVVLPTNNSVSGELILEELEVFKNHAPITTMKISSKKQQLYVSSNEGVS' \
                    'QVSLHRCHIYGTACADCCLARDPYCAWDGHSCSRFYPTGKRRSRRQDVRHGNPLTQCR'
    FASTA_SEQ_1_B = 'RVYLTFDELRETKTSEYFSLSHHPLDYRILLMDEDQDRIYVGSKDHILSLNINNISQEALSVFWPASTIKVEECKMAGKDPTHGCGNFVRVIQTFN' \
                    'RTHLYVCGSGAFSPVCTYLNRGRRSEDQVFMIDSKCESGKGRCSFNPNVNTVSVMINEELFSGMYIDFMGTDAAIFRSLTKRNAVRTDQHNSKWLS' \
                    'EPMFVDAHVIPDGTDPNDAKVYFFFKEKLTDNNRSTKQIHSMIARICPNDTGGLRSLVNKWTTFLKARLVCSVTDEDGPETHFDELEDVFLLETDN' \
                    'PRTTLVYGIFTTSSSVFKGSAVCVYHLSDIQTVFNGPFAHKEGPNHQLISYQGRIPYPRPGTCPGGAFTPNMRTTKEFPDDVVTFIRNHPLMYNSI' \
                    'YPIHKRPLIVRIGTDYKYTKIAVDRVNAADGRYHVLFLGTDRGTVQKVVVLPTNNSVSGELILEELEVFKNHAPITTMKISSKKQQLYVSSNEGVS' \
                    'QVSLHRCHIYGTACADCCLARDPYCAWDGHSCSRFYPTGKRRSRRQDVRHGNPLTQCR'
    FASTA_SEQ_2_A = 'EIVQYGVKNNTTFLECAPKSPQASIKWLLQKDKDRRKEVKLNERIIATSQGLLIRSVQGSDQGLYHCIATENSFKQTIAKINFKVLD'
    FASTA_SEQ_3_A = 'RVYLTFDELRETKTSEYFSLSHHPLDYRILLMDEDQDRIYVGSKDHILSLNINNISQEALSVFWPASTIKVEECKMAGKDPTHGCGNFVRVIQTFN' \
                    'RTHLYVCGSGAFSPVCTYLNRGRRSEDQVFMIDSKCESGKGRCSFNPNVNTVSVMINEELFSGMYIDFMGTDAAIFRSLTKRNAVRTDQHNSKWLS' \
                    'EPMFVDAHVIPDGTDPNDAKVYFFFKEKLTDNNRSTKQIHSMIARICPNDTGGLRSLVNKWTTFLKARLVCSVTDEDGPETHFDELEDVFLLETDN' \
                    'PRTTLVYGIFTTSSSVFKGSAVCVYHLSDIQTVFNGPFAHKEGPNHQLISYQGRIPYPRPGTCPGGAFTPNMRTTKEFPDDVVTFIRNHPLMYNSI' \
                    'YPIHKRPLIVRIGTDYKYTKIAVDRVNAADGRYHVLFLGTDRGTVQKVVVLPTNNSVSGELILEELEVFKNHAPITTMKISSKKQQLYVSSNEGVS' \
                    'QVSLHRCHIYGTACADCCLARDPYCAWDGHSCSRFYPTGKRRSRRQDVRHGNPLTQCR'
    FASTA_SEQ_3_B = 'RVYLTFDELRETKTSEYFSLSHHPLDYRILLMDEDQDRIYVGSKDHILSLNINNISQEALSVFWPASTIKVEECKMAGKDPTHGCGNFVRVIQTFN' \
                    'RTHLYVCGSGAFSPVCTYLNRGRRSEDQVFMIDSKCESGKGRCSFNPNVNTVSVMINEELFSGMYIDFMGTDAAIFRSLTKRNAVRTDQHNSKWLS' \
                    'EPMFVDAHVIPDGTDPNDAKVYFFFKEKLTDNNRSTKQIHSMIARICPNDTGGLRSLVNKWTTFLKARLVCSVTDEDGPETHFDELEDVFLLETDN' \
                    'PRTTLVYGIFTTSSSVFKGSAVCVYHLSDIQTVFNGPFAHKEGPNHQLISYQGRIPYPRPGTCPGGAFTPNMRTTKEFPDDVVTFIRNHPLMYNSI' \
                    'YPIHKRPLIVRIGTDYKYTKIAVDRVNAADGRYHVLFLGTDRGTVQKVVVLPTNNSVSGELILEELEVFKNHAPITTMKISSKKQQLYVSSNEGVS' \
                    'QVSLHRCHIYGTACADCCLARDPYCAWDGHSCSRFYPTGKRRSRRQDVRHGNPLTQCR'
    FASTA_SEQ_10_B = 'SCIQFTRHASDVLLNLNRLRSRDILTDVVIVVSREQFRAHKTVLMACSGLFYSIFTDQLKCNLSVINLDPEINPEGFCILLDFMYTSRLNLREGN' \
                     'IMAVMATAMYLQMEHVVDTCRKFIKAS'
    FASTA_SEQ_MIN_WT = 'SCI'
    FASTA_SEQ_MIN_S1A = 'ACI'
    FASTA_SEQ_MIN_S1C = 'CCI'
    FASTA_SEQ_MIN_S1D = 'DCI'
    FASTA_SEQ_MIN_S1E = 'ECI'
    FASTA_SEQ_MIN_S1F = 'FCI'
    FASTA_SEQ_MIN_S1G = 'GCI'
    FASTA_SEQ_MIN_S1H = 'HCI'
    FASTA_SEQ_MIN_S1I = 'ICI'
    FASTA_SEQ_MIN_S1K = 'KCI'
    FASTA_SEQ_MIN_S1L = 'LCI'
    FASTA_SEQ_MIN_S1M = 'MCI'
    FASTA_SEQ_MIN_S1N = 'NCI'
    FASTA_SEQ_MIN_S1P = 'PCI'
    FASTA_SEQ_MIN_S1Q = 'QCI'
    FASTA_SEQ_MIN_S1R = 'RCI'
    FASTA_SEQ_MIN_S1S = 'SCI'
    FASTA_SEQ_MIN_S1T = 'TCI'
    FASTA_SEQ_MIN_S1V = 'VCI'
    FASTA_SEQ_MIN_S1W = 'WCI'
    FASTA_SEQ_MIN_S1Y = 'YCI'

    FASTA_SEQ_MIN_C2A = 'SAI'
    FASTA_SEQ_MIN_C2C = 'SCI'
    FASTA_SEQ_MIN_C2D = 'SDI'
    FASTA_SEQ_MIN_C2E = 'SEI'
    FASTA_SEQ_MIN_C2F = 'SFI'
    FASTA_SEQ_MIN_C2G = 'SGI'
    FASTA_SEQ_MIN_C2H = 'SHI'
    FASTA_SEQ_MIN_C2I = 'SII'
    FASTA_SEQ_MIN_C2K = 'SKI'
    FASTA_SEQ_MIN_C2L = 'SLI'
    FASTA_SEQ_MIN_C2M = 'SMI'
    FASTA_SEQ_MIN_C2N = 'SNI'
    FASTA_SEQ_MIN_C2P = 'SPI'
    FASTA_SEQ_MIN_C2Q = 'SQI'
    FASTA_SEQ_MIN_C2R = 'SRI'
    FASTA_SEQ_MIN_C2S = 'SSI'
    FASTA_SEQ_MIN_C2T = 'STI'
    FASTA_SEQ_MIN_C2V = 'SVI'
    FASTA_SEQ_MIN_C2W = 'SWI'
    FASTA_SEQ_MIN_C2Y = 'SYI'

    FASTA_SEQ_MIN_I3A = 'SCA'
    FASTA_SEQ_MIN_I3C = 'SCC'
    FASTA_SEQ_MIN_I3D = 'SCD'
    FASTA_SEQ_MIN_I3E = 'SCE'
    FASTA_SEQ_MIN_I3F = 'SCF'
    FASTA_SEQ_MIN_I3G = 'SCG'
    FASTA_SEQ_MIN_I3H = 'SCH'
    FASTA_SEQ_MIN_I3I = 'SCI'
    FASTA_SEQ_MIN_I3K = 'SCK'
    FASTA_SEQ_MIN_I3L = 'SCL'
    FASTA_SEQ_MIN_I3M = 'SCM'
    FASTA_SEQ_MIN_I3N = 'SCN'
    FASTA_SEQ_MIN_I3P = 'SCP'
    FASTA_SEQ_MIN_I3Q = 'SCQ'
    FASTA_SEQ_MIN_I3R = 'SCR'
    FASTA_SEQ_MIN_I3S = 'SCS'
    FASTA_SEQ_MIN_I3T = 'SCT'
    FASTA_SEQ_MIN_I3V = 'SCV'
    FASTA_SEQ_MIN_I3W = 'SCW'
    FASTA_SEQ_MIN_I3Y = 'SCY'
