ROOT:
    path_R_exe: '/software/shared/apps/general/R/3.1.2/bin/Rscript'
    path_FoldX_exe: '/switchlab/group/tools/FoldX_2015/FoldX'
    path_Agadir_exe: '/switchlab/group/tools/agadir_10042012/agadirwrapper'
    path_Qsub_exe: '/opt/sge/bin/lx-amd64/'
    path_local_FoldX_exe: '/Users/u0120577/PycharmProjects'
    path_local_Agadir_exe: '/Users/u0120577/PycharmProjects'
    path_local_R_exe: '/usr/local/Cellar/r/3.5.0'

    path_SnpEffect_dir: '/switchlab/group/shazib/SnpEffect'
    path_SE_SourceFiles_Scripts_dir: '/switchlab/group/shazib/SnpEffect/SourceFiles/Scripts'
    path_SE_PDBs_Inputs_dir: '/switchlab/group/shazib/SnpEffect/PDBs/Inputs'
    path_SE_Outputs_dir: '/switchlab/group/shazib/SnpEffect/Outputs'
    path_SE_Outputs_Agadir_dir: '/switchlab/group/shazib/SnpEffect/Outputs/Agadir'
    path_SE_Outputs_FoldX_dir: '/switchlab/group/shazib/SnpEffect/Outputs/FoldX'

    aa_dict_1to3:
        A: ALA
        C: CYS
        D: ASP
        E: GLU
        F: PHE
        G: GLY
        H: HIS
        I: ILE
        K: LYS
        L: LEU
        M: MET
        N: ASN
        P: PRO
        Q: GLN
        R: ARG
        S: SER
        T: THR
        V: VAL
        W: TRP
        Y: TYR

    aa_dict_3to1:
        ALA: A
        CYS: C
        ASP: D
        GLU: E
        PHE: F
        GLY: G
        HIS: H
        H1S: H
        H2S: H
        ILE: I
        LYS: K
        LEU: L
        MET: M
        ASN: N
        PRO: P
        GLN: Q
        ARG: R
        SER: S
        THR: T
        VAL: V
        TRP: W
        TYR: Y

    list_all_20_aa:
        - A
        - C
        - D
        - E
        - F
        - G
        - H
        - I
        - K
        - L
        - M
        - N
        - P
        - Q
        - R
        - S
        - T
        - V
        - W
        - Y





