ROOT:
    path_R: '/software/shared/apps/general/R/3.1.2/bin/Rscript'
    path_FoldX: '/switchlab/group/tools/FoldX_2015/FoldX'
    path_Agadir: '/switchlab/group/tools/agadir_10042012/agadirwrapper'
    path_Qsub: '/opt/sge/bin/lx-amd64/'
    path_local_FoldX: '/Users/u0120577/PycharmProjects'
    path_local_Agadir: '/Users/u0120577/PycharmProjects'
    path_local_R: '/usr/local/Cellar/r/3.5.0'

    path_start: '/switchlab/group/shazib/OptimizeProteinShazibCopy'
    path_scripts: '/switchlab/group/shazib/OptimizeProteinShazibCopy/SourceFiles/Scripts'
    path_results: '/switchlab/group/shazib/OptimizeProteinShazibCopy/Results'

    aa_dict_1to3:
        A: ALA
        C: CYS
        D: ASP
        E: GLU
        F: PHE
        G: GLY
        H: HIS
        I: ILE
        K: LYS
        L: LEU
        M: MET
        N: ASN
        P: PRO
        Q: GLN
        R: ARG
        S: SER
        T: THR
        V: VAL
        W: TRP
        Y: TYR
    aa_dict_3to1:
        ALA: A
        CYS: C
        ASP: D
        GLU: E
        PHE: F
        GLY: G
        HIS: H
        H1S: H
        H2S: H
        ILE: I
        LYS: K
        LEU: L
        MET: M
        ASN: N
        PRO: P
        GLN: Q
        ARG: R
        SER: S
        THR: T
        VAL: V
        TRP: W
        TYR: Y

    all_20_residues:
        - A
        - C
        - D
        - E
        - F
        - G
        - H
        - I
        - K
        - L
        - M
        - N
        - P
        - Q
        - R
        - S
        - T
        - V
        - W
        - Y





