ROOT:
    path_zeus_R_exe: '/software/shared/apps/general/R/3.1.2/bin/Rscript'
    path_zeus_FoldX_exe: '/switchlab/group/tools/FoldX_2015/FoldX'
    path_zeus_Agadir_exe: '/switchlab/group/tools/agadir_10042012/agadirwrapper'
    path_zeus_Qsub_exe: '/opt/sge/bin/lx-amd64/'

    path_local_R_exe: '/usr/local/bin/R'
    path_local_FoldX_exe: '/Users/u0120577/SNPEFFECT/executables/FoldX'
    path_local_Agadir_exe: '/Users/u0120577/SNPEFFECT/executables/agadirwrapper'

    path_zeus_SnpEffect: '/switchlab/group/shazib/SnpEffect'
    path_zeus_SE_SourceFiles_Scripts: '/switchlab/group/shazib/SnpEffect/SourceFiles/Scripts'
    path_zeus_SE_Inputs_PDBs: '/switchlab/group/shazib/SnpEffect/Inputs/PDBs'
    path_zeus_SE_Inputs_FASTAs: '/switchlab/group/shazib/SnpEffect/Inputs/FASTAs'
    path_zeus_SE_Outputs: '/switchlab/group/shazib/SnpEffect/Outputs'
    path_zeus_SE_Outputs_Agadir: '/switchlab/group/shazib/SnpEffect/Outputs/Agadir'
    path_zeus_SE_Outputs_FoldX: '/switchlab/group/shazib/SnpEffect/Outputs/FoldX'

    path_local_MutateCompute: '/Users/u0120577/PycharmProjects/MutateCompute'
    path_local_MC_src: '/Users/u0120577/PycharmProjects/MutateCompute/src'
    path_local_MC_tests_Inputs: '/Users/u0120577/PycharmProjects/MutateCompute/tests/Inputs'
    path_local_MC_tests_Inputs_FoldX: '/Users/u0120577/PycharmProjects/MutateCompute/tests/Inputs/FoldX'
    path_local_MC_tests_Inputs_Agadir: '/Users/u0120577/PycharmProjects/MutateCompute/tests/Inputs/Agadir'
    path_local_MC_tests_Inputs_PDBs: '/Users/u0120577/PycharmProjects/MutateCompute/tests/Inputs/PDBs'
    path_local_MC_tests_Inputs_FASTA: '/Users/u0120577/PycharmProjects/MutateCompute/tests/Inputs/Fasta'
    path_local_MC_tests_Outputs: '/Users/u0120577/PycharmProjects/MutateCompute/tests/Outputs'
    path_local_MC_tests_Outputs_Agadir: '/Users/u0120577/PycharmProjects/MutateCompute/tests/Outputs/Agadir'
    path_local_MC_tests_Outputs_FoldX: '/Users/u0120577/PycharmProjects/MutateCompute/tests/Outputs/FoldX'


    dict_aa_1to3:
        A: ALA
        C: CYS
        D: ASP
        E: GLU
        F: PHE
        G: GLY
        H: HIS
        I: ILE
        K: LYS
        L: LEU
        M: MET
        N: ASN
        P: PRO
        Q: GLN
        R: ARG
        S: SER
        T: THR
        V: VAL
        W: TRP
        Y: TYR

    dict_aa_3to1:
        ALA: A
        CYS: C
        ASP: D
        GLU: E
        PHE: F
        GLY: G
        HIS: H
        H1S: H
        H2S: H
        ILE: I
        LYS: K
        LEU: L
        MET: M
        ASN: N
        PRO: P
        GLN: Q
        ARG: R
        SER: S
        THR: T
        VAL: V
        TRP: W
        TYR: Y

    list_all_20_aa:
        - A
        - C
        - D
        - E
        - F
        - G
        - H
        - I
        - K
        - L
        - M
        - N
        - P
        - Q
        - R
        - S
        - T
        - V
        - W
        - Y