ROOT:
    # path to executables on cluster and local
    path_zeus_R_exe: '/software/shared/apps/general/R/3.1.2/bin/Rscript'
    path_zeus_FoldX_exe: '/switchlab/group/tools/FoldX_2015/FoldX'
    path_zeus_Agadir_exe: '/switchlab/group/tools/agadir_10042012/agadirwrapper'
    path_zeus_Qsub_exe: '/opt/sge/bin/lx-amd64/'
    path_local_R_exe: '/usr/local/bin/R'
    path_local_FoldX_exe: '/Users/u0120577/SNPEFFECT/executables/FoldX'
    path_local_Agadir_exe: '/Users/u0120577/SNPEFFECT/executables/agadirwrapper'

    # root directories of cluster and local trees
    path_zeus_SnpEffect: '/switchlab/group/shazib/SnpEffect'
    path_local_MutateCompute: '/Users/u0120577/PycharmProjects/MutateCompute'

    # relative paths - common to both cluster and local trees - these are specific to unit tests
    path_rel_src: '/src'
    path_rel_tests_Inputs_PDBs: '/tests/Inputs/PDBs'
    path_rel_tests_Inputs_Fasta: '/tests/Inputs/Fasta'
    path_rel_tests_Inputs_Options: '/tests/Inputs/Options'
    path_rel_tests_Outputs_PDBs: '/tests/Outputs/PDBs'
    path_rel: '/'
    path_rel_Cluster: '/Cluster'
    path_rel_Agadir: '/Agadir'
    path_rel_FoldX: '/FoldX'
    path_rel_FoldX_BuildModel: '/FoldX/BuildModel'
    path_rel_FoldX_Repair: '/FoldX/Repair'
    path_rel_FoldX_AnalyseComplex: '/FoldX/AnalyseComplex'

    dict_aa_1to3:
        A: ALA
        C: CYS
        D: ASP
        E: GLU
        F: PHE
        G: GLY
        H: HIS
        I: ILE
        K: LYS
        L: LEU
        M: MET
        N: ASN
        P: PRO
        Q: GLN
        R: ARG
        S: SER
        T: THR
        V: VAL
        W: TRP
        Y: TYR

    dict_aa_3to1:
        ALA: A
        CYS: C
        ASP: D
        GLU: E
        PHE: F
        GLY: G
        HIS: H
        H1S: H
        H2S: H
        ILE: I
        LYS: K
        LEU: L
        MET: M
        ASN: N
        PRO: P
        GLN: Q
        ARG: R
        SER: S
        THR: T
        VAL: V
        TRP: W
        TYR: Y

    list_all_20_aa:
        - A
        - C
        - D
        - E
        - F
        - G
        - H
        - I
        - K
        - L
        - M
        - N
        - P
        - Q
        - R
        - S
        - T
        - V
        - W
        - Y